export const HOME = '/'
export const CART = '/cart'
export const AUTH = '/auth'
export const LOG_IN = '/login'
export const SIGN_UP = '/signup'
export const ACCOUNT = '/account'
export const STYLE_GUIDE = '/style-guide'
